$:.unshift(File.dirname(__FILE__) + '/../../rspec/lib')
require 'rubygems'
require 'rspec/core/rake_task'

desc "Run all specs"
Rspec::Core::RakeTask.new do |t|
  t.rcov = true
  t.rcov_opts = ['--exclude', 'rspec\/plugins,rspec\/lib\/spec,spec\/spec,fixtures,bin\/spec']
end


Dir['bundle_tasks/**/*.rake'].each { |rake| load rake }




