<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>injectionSelector</key>
	<string>L:text.html.markdown</string>
	<key>name</key>
	<string>Markdown Fenced Code Blocks</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^``` *(\w+) *$</string>
			<key>contentName</key>
			<string>meta.embedded_$1.markdown</string>
			<key>end</key>
			<string>^``` *\n?</string>
			<key>name</key>
			<string>markup.raw.block.markdown</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>injection.markdown.highlight</string>
	<key>uuid</key>
	<string>8D30AC8B-2D2B-4BCE-9200-E96191422139</string>
</dict>
</plist>
