<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>changed</key>
	<dict>
		<key>patterns</key>
		<array>
			<dict>
				<key>include</key>
				<string>#frontmatter</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#block</string>
			</dict>
		</array>
		<key>repository.frontmatter</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?:^|\G)---\s*\n</string>
					<key>end</key>
					<string>(?:^|\G)---\s*\n</string>
					<key>name</key>
					<string>markup.raw.block.frontmatter.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.frontmatter</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?:^|\G)(\w+:).*$</string>
							<key>name</key>
							<string>string.unquoted.frontmatter</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:^|\G)</string>
					<key>end</key>
					<string>(?not)possible</string>
					<key>name</key>
					<string>meta.markdown.after-frontmatter</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>isDelta</key>
	<true/>
	<key>uuid</key>
	<string>0A1D9874-B448-11D9-BD50-000D93B6E43C</string>
</dict>
</plist>
