<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>a</string>
	</array>
	<key>name</key>
	<string>ACME Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>!(16|24|32|8|addr|al|align|as|binary|byte|convtab|cpu|do|endoffile|error|fill|for|if|ifdef|ifndef|initmem|macro|pet|pseudopc|raw|rl|rs|scr|scrxor|serious|set|source|symbollist|text|to|warn|word|zone)\b</string>
			<key>name</key>
			<string>keyword.other.directive</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.macro.identifier</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.macro</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.macro</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*((\.macro)\s*([A-Za-z_][A-Za-z0-9_]*))\b</string>
			<key>name</key>
			<string>macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(adc|and|asl|bit|clc|cld|cli|clv|cmp|cpx|cpy|dec|dex|dey|eor|inc|inx|iny|lda|ldx|ldy|lsr|nop|ora|pha|php|pla|plp|rol|ror|sbc|sec|sed|sei|sta|stx|sty|tax|txa|tay|tya|tsx|txs)\b</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(aac|aax|alr|anc|ane|arr|aso|asr|atx|axa|axs|dcm|dcp|dop|hlt|ins|isb|isc|jam|kil|lae|lar|las|lax|lse|lxa|oal|rla|rra|sax|sbx|skb|sha|shs|say|shx|shy|slo|skw|sre|sxa|sya|tas|top|xaa|xas)\b</string>
			<key>name</key>
			<string>illegal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bcc|bcs|beq|bmi|bne|bpl|brk|bvc|bvs|jmp|jsr|rti|rts)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>;</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.semicolon.avrasm</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.label</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(!|(^\w))\w+(:|-|\+)</string>
			<key>name</key>
			<string>label</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\.\b(var|fill|pc)\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(SET|WORD|BYTE|HEX)\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ALIGN)\b</string>
			<key>name</key>
			<string>storage.modifier</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(REPEAT|REPEND|MAC|ENDM|SUBROUTINE)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(processor|org)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^[A-Za-z_][A-Za-z0-9_]*</string>
			<key>name</key>
			<string>entity.name.label</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\.[A-Za-z_][A-Za-z0-9_]*</string>
			<key>name</key>
			<string>entity.name.label.local</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#?\$[0-9a-fA-F]+</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#[0-9a-fA-F]+\b</string>
			<key>name</key>
			<string>constant.numeric.decimal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+\b</string>
			<key>name</key>
			<string>constant.numeric.decimal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#%[0-1]+\b</string>
			<key>name</key>
			<string>constant.numeric.binary</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.6502asm.acme</string>
	<key>uuid</key>
	<string>A59CF427-6B96-45D2-89C2-478DBA4D4D0F</string>
</dict>
</plist>
